POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "userId": "admin",
  "password": "admin"
}

> {%
 client.global.set("accessTokenAdmin", "Bearer " + response.body.accessToken);
 client.log("accessTokenAdmin: " + client.global.get("accessTokenAdmin"));
 %}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "userId": "user",
  "password": "user"
}

> {%
 client.global.set("accessTokenUser", "Bearer " + response.body.accessToken);
 client.log("accessTokenUser: " + client.global.get("accessTokenUser"));
 %}